// PLACEHOLDER DATA, generated by scripts/generate-placeholder-products.mjs.
// Replace with the real catalog; keep the Product shape.
import type { Product } from "@/lib/data/types";

export const doorsWindowsTrimProducts: Product[] = [
  {
    "id": "doors-windows-trim-001",
    "name": "2-Panel Shaker Prehung Door",
    "slug": "2-panel-shaker-prehung-door",
    "category": "doors-windows-trim",
    "subcategory": "interior-doors",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Style",
        "value": "2-panel shaker"
      },
      {
        "key": "Core",
        "value": "Solid core"
      },
      {
        "key": "Size",
        "value": "30 × 80 in"
      },
      {
        "key": "Finish",
        "value": "Primed"
      }
    ],
    "tags": [
      "shaker",
      "solid-core"
    ],
    "images": [
      {
        "src": "/images/products/interior-doors/2-panel-shaker-prehung-door.svg",
        "alt": "2-Panel Shaker Prehung Door (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "door-installation-repair"
  },
  {
    "id": "doors-windows-trim-002",
    "name": "Flat-Panel Hollow Core Slab",
    "slug": "flat-panel-hollow-core-slab",
    "category": "doors-windows-trim",
    "subcategory": "interior-doors",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Style",
        "value": "Flush"
      },
      {
        "key": "Core",
        "value": "Hollow"
      },
      {
        "key": "Size",
        "value": "32 × 80 in"
      },
      {
        "key": "Finish",
        "value": "Primed"
      }
    ],
    "tags": [
      "modern",
      "budget"
    ],
    "images": [
      {
        "src": "/images/products/interior-doors/flat-panel-hollow-core-slab.svg",
        "alt": "Flat-Panel Hollow Core Slab (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "door-installation-repair"
  },
  {
    "id": "doors-windows-trim-003",
    "name": "Fiberglass Entry Door, 3/4 Lite",
    "slug": "fiberglass-entry-door-3-4-lite",
    "category": "doors-windows-trim",
    "subcategory": "exterior-doors",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Material",
        "value": "Fiberglass"
      },
      {
        "key": "Glass",
        "value": "3/4 lite, low-E"
      },
      {
        "key": "Size",
        "value": "36 × 80 in"
      }
    ],
    "tags": [
      "fiberglass",
      "entry"
    ],
    "images": [
      {
        "src": "/images/products/exterior-doors/fiberglass-entry-door-3-4-lite.svg",
        "alt": "Fiberglass Entry Door, 3/4 Lite (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "door-installation-repair"
  },
  {
    "id": "doors-windows-trim-004",
    "name": "Sliding Patio Door",
    "slug": "sliding-patio-door",
    "category": "doors-windows-trim",
    "subcategory": "exterior-doors",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Material",
        "value": "Vinyl"
      },
      {
        "key": "Glass",
        "value": "Dual-pane low-E"
      },
      {
        "key": "Size",
        "value": "72 × 80 in"
      }
    ],
    "tags": [
      "patio",
      "low-e"
    ],
    "images": [
      {
        "src": "/images/products/exterior-doors/sliding-patio-door.svg",
        "alt": "Sliding Patio Door (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "door-installation-repair"
  },
  {
    "id": "doors-windows-trim-005",
    "name": "5-1/4 in Colonial Baseboard (MDF)",
    "slug": "5-1-4-in-colonial-baseboard-mdf",
    "category": "doors-windows-trim",
    "subcategory": "baseboards-casing",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Height",
        "value": "5.25 in"
      },
      {
        "key": "Material",
        "value": "Primed MDF"
      },
      {
        "key": "Length",
        "value": "16 ft"
      }
    ],
    "tags": [
      "mdf",
      "colonial"
    ],
    "images": [
      {
        "src": "/images/products/baseboards-casing/5-1-4-in-colonial-baseboard-mdf.svg",
        "alt": "5-1/4 in Colonial Baseboard (MDF) (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "baseboards-trim-carpentry"
  },
  {
    "id": "doors-windows-trim-006",
    "name": "3-1/2 in Flat Modern Baseboard",
    "slug": "3-1-2-in-flat-modern-baseboard",
    "category": "doors-windows-trim",
    "subcategory": "baseboards-casing",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Height",
        "value": "3.5 in"
      },
      {
        "key": "Material",
        "value": "Primed MDF"
      },
      {
        "key": "Length",
        "value": "16 ft"
      }
    ],
    "tags": [
      "mdf",
      "modern"
    ],
    "images": [
      {
        "src": "/images/products/baseboards-casing/3-1-2-in-flat-modern-baseboard.svg",
        "alt": "3-1/2 in Flat Modern Baseboard (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "baseboards-trim-carpentry"
  },
  {
    "id": "doors-windows-trim-007",
    "name": "2-1/4 in Colonial Casing",
    "slug": "2-1-4-in-colonial-casing",
    "category": "doors-windows-trim",
    "subcategory": "baseboards-casing",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Width",
        "value": "2.25 in"
      },
      {
        "key": "Material",
        "value": "Primed MDF"
      },
      {
        "key": "Length",
        "value": "7 ft"
      }
    ],
    "tags": [
      "mdf",
      "casing"
    ],
    "images": [
      {
        "src": "/images/products/baseboards-casing/2-1-4-in-colonial-casing.svg",
        "alt": "2-1/4 in Colonial Casing (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "baseboards-trim-carpentry"
  },
  {
    "id": "doors-windows-trim-008",
    "name": "3-5/8 in Crown (MDF)",
    "slug": "3-5-8-in-crown-mdf",
    "category": "doors-windows-trim",
    "subcategory": "crown-moulding",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Height",
        "value": "3.625 in"
      },
      {
        "key": "Material",
        "value": "Primed MDF"
      },
      {
        "key": "Length",
        "value": "16 ft"
      }
    ],
    "tags": [
      "mdf",
      "crown"
    ],
    "images": [
      {
        "src": "/images/products/crown-moulding/3-5-8-in-crown-mdf.svg",
        "alt": "3-5/8 in Crown (MDF) (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "baseboards-trim-carpentry"
  },
  {
    "id": "doors-windows-trim-009",
    "name": "5-1/4 in Crown (Pine)",
    "slug": "5-1-4-in-crown-pine",
    "category": "doors-windows-trim",
    "subcategory": "crown-moulding",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Height",
        "value": "5.25 in"
      },
      {
        "key": "Material",
        "value": "Finger-joint pine"
      },
      {
        "key": "Length",
        "value": "16 ft"
      }
    ],
    "tags": [
      "pine",
      "crown"
    ],
    "images": [
      {
        "src": "/images/products/crown-moulding/5-1-4-in-crown-pine.svg",
        "alt": "5-1/4 in Crown (Pine) (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "baseboards-trim-carpentry"
  }
];
