// PLACEHOLDER DATA — generated by scripts/generate-placeholder-products.mjs.
// Replace with the real catalog; keep the Product shape.
import type { Product } from "@/lib/data/types";

export const drywallMaterialsProducts: Product[] = [
  {
    "id": "drywall-materials-001",
    "name": "1/2 in Standard Drywall 4x8",
    "slug": "1-2-in-standard-drywall-4x8",
    "category": "drywall-materials",
    "subcategory": "drywall-sheets",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "1/2 in"
      },
      {
        "key": "Size",
        "value": "4 × 8 ft"
      },
      {
        "key": "Use",
        "value": "Walls"
      }
    ],
    "tags": [
      "standard"
    ],
    "images": [
      {
        "src": "/images/products/drywall-sheets/1-2-in-standard-drywall-4x8.svg",
        "alt": "1/2 in Standard Drywall 4x8 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "drywall-repair-installation"
  },
  {
    "id": "drywall-materials-002",
    "name": "5/8 in Type X Fire-Rated 4x8",
    "slug": "5-8-in-type-x-fire-rated-4x8",
    "category": "drywall-materials",
    "subcategory": "drywall-sheets",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "5/8 in"
      },
      {
        "key": "Size",
        "value": "4 × 8 ft"
      },
      {
        "key": "Use",
        "value": "Ceilings, garage walls"
      }
    ],
    "tags": [
      "fire-rated"
    ],
    "images": [
      {
        "src": "/images/products/drywall-sheets/5-8-in-type-x-fire-rated-4x8.svg",
        "alt": "5/8 in Type X Fire-Rated 4x8 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "drywall-repair-installation"
  },
  {
    "id": "drywall-materials-003",
    "name": "1/2 in Moisture-Resistant 4x8",
    "slug": "1-2-in-moisture-resistant-4x8",
    "category": "drywall-materials",
    "subcategory": "drywall-sheets",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "1/2 in"
      },
      {
        "key": "Size",
        "value": "4 × 8 ft"
      },
      {
        "key": "Use",
        "value": "Bathrooms, laundry"
      }
    ],
    "tags": [
      "moisture-resistant"
    ],
    "images": [
      {
        "src": "/images/products/drywall-sheets/1-2-in-moisture-resistant-4x8.svg",
        "alt": "1/2 in Moisture-Resistant 4x8 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "drywall-repair-installation"
  },
  {
    "id": "drywall-materials-004",
    "name": "All-Purpose Joint Compound",
    "slug": "all-purpose-joint-compound",
    "category": "drywall-materials",
    "subcategory": "joint-compound-texture",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "4.5 gal"
      },
      {
        "key": "Type",
        "value": "Pre-mixed"
      },
      {
        "key": "Use",
        "value": "Tape and finish coats"
      }
    ],
    "tags": [
      "pre-mixed"
    ],
    "images": [
      {
        "src": "/images/products/joint-compound-texture/all-purpose-joint-compound.svg",
        "alt": "All-Purpose Joint Compound (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "drywall-repair-installation"
  },
  {
    "id": "drywall-materials-005",
    "name": "Setting-Type Compound, 45-minute",
    "slug": "setting-type-compound-45-minute",
    "category": "drywall-materials",
    "subcategory": "joint-compound-texture",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "18 lb"
      },
      {
        "key": "Type",
        "value": "Powder"
      },
      {
        "key": "Use",
        "value": "First coat, repairs"
      }
    ],
    "tags": [
      "setting-type"
    ],
    "images": [
      {
        "src": "/images/products/joint-compound-texture/setting-type-compound-45-minute.svg",
        "alt": "Setting-Type Compound, 45-minute (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "drywall-repair-installation"
  },
  {
    "id": "drywall-materials-006",
    "name": "Orange Peel Spray Texture",
    "slug": "orange-peel-spray-texture",
    "category": "drywall-materials",
    "subcategory": "joint-compound-texture",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "20 oz aerosol"
      },
      {
        "key": "Pattern",
        "value": "Orange peel"
      },
      {
        "key": "Use",
        "value": "Small patches"
      }
    ],
    "tags": [
      "texture"
    ],
    "images": [
      {
        "src": "/images/products/joint-compound-texture/orange-peel-spray-texture.svg",
        "alt": "Orange Peel Spray Texture (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "drywall-repair-installation"
  },
  {
    "id": "drywall-materials-007",
    "name": "R-13 Kraft-Faced Batt",
    "slug": "r-13-kraft-faced-batt",
    "category": "drywall-materials",
    "subcategory": "insulation",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "R-value",
        "value": "R-13"
      },
      {
        "key": "Width",
        "value": "15 in"
      },
      {
        "key": "Use",
        "value": "2×4 walls"
      }
    ],
    "tags": [
      "batt"
    ],
    "images": [
      {
        "src": "/images/products/insulation/r-13-kraft-faced-batt.svg",
        "alt": "R-13 Kraft-Faced Batt (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "drywall-repair-installation"
  },
  {
    "id": "drywall-materials-008",
    "name": "R-38 Blown-In Cellulose",
    "slug": "r-38-blown-in-cellulose",
    "category": "drywall-materials",
    "subcategory": "insulation",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "R-value",
        "value": "R-38"
      },
      {
        "key": "Type",
        "value": "Blown-in"
      },
      {
        "key": "Use",
        "value": "Attics"
      }
    ],
    "tags": [
      "blown-in",
      "attic"
    ],
    "images": [
      {
        "src": "/images/products/insulation/r-38-blown-in-cellulose.svg",
        "alt": "R-38 Blown-In Cellulose (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "drywall-repair-installation"
  }
];
