// PLACEHOLDER DATA — generated by scripts/generate-placeholder-products.mjs.
// Replace with the real catalog; keep the Product shape.
import type { Product } from "@/lib/data/types";

export const electricalLightingProducts: Product[] = [
  {
    "id": "electrical-lighting-001",
    "name": "52-inch Indoor Ceiling Fan with LED",
    "slug": "52-inch-indoor-ceiling-fan-with-led",
    "category": "electrical-lighting",
    "subcategory": "ceiling-fans",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "52 in"
      },
      {
        "key": "Motor",
        "value": "DC"
      },
      {
        "key": "Light",
        "value": "Integrated LED"
      },
      {
        "key": "Control",
        "value": "Remote"
      }
    ],
    "tags": [
      "indoor",
      "led",
      "remote"
    ],
    "images": [
      {
        "src": "/images/products/ceiling-fans/52-inch-indoor-ceiling-fan-with-led.svg",
        "alt": "52-inch Indoor Ceiling Fan with LED (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "lighting-ceiling-fan-installation"
  },
  {
    "id": "electrical-lighting-002",
    "name": "60-inch Outdoor Damp-Rated Fan",
    "slug": "60-inch-outdoor-damp-rated-fan",
    "category": "electrical-lighting",
    "subcategory": "ceiling-fans",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "60 in"
      },
      {
        "key": "Motor",
        "value": "DC"
      },
      {
        "key": "Rating",
        "value": "Damp"
      },
      {
        "key": "Control",
        "value": "Remote"
      }
    ],
    "tags": [
      "outdoor",
      "damp-rated"
    ],
    "images": [
      {
        "src": "/images/products/ceiling-fans/60-inch-outdoor-damp-rated-fan.svg",
        "alt": "60-inch Outdoor Damp-Rated Fan (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "lighting-ceiling-fan-installation"
  },
  {
    "id": "electrical-lighting-003",
    "name": "6-inch Slim LED Recessed Light",
    "slug": "6-inch-slim-led-recessed-light",
    "category": "electrical-lighting",
    "subcategory": "recessed-lighting",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "6 in"
      },
      {
        "key": "Output",
        "value": "1100 lm"
      },
      {
        "key": "CCT",
        "value": "Selectable 2700–5000K"
      },
      {
        "key": "Dimmable",
        "value": "Yes"
      }
    ],
    "tags": [
      "led",
      "dimmable",
      "selectable-cct"
    ],
    "images": [
      {
        "src": "/images/products/recessed-lighting/6-inch-slim-led-recessed-light.svg",
        "alt": "6-inch Slim LED Recessed Light (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "lighting-ceiling-fan-installation"
  },
  {
    "id": "electrical-lighting-004",
    "name": "4-inch Slim LED Recessed Light",
    "slug": "4-inch-slim-led-recessed-light",
    "category": "electrical-lighting",
    "subcategory": "recessed-lighting",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "4 in"
      },
      {
        "key": "Output",
        "value": "750 lm"
      },
      {
        "key": "CCT",
        "value": "Selectable 2700–5000K"
      },
      {
        "key": "Dimmable",
        "value": "Yes"
      }
    ],
    "tags": [
      "led",
      "dimmable"
    ],
    "images": [
      {
        "src": "/images/products/recessed-lighting/4-inch-slim-led-recessed-light.svg",
        "alt": "4-inch Slim LED Recessed Light (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "lighting-ceiling-fan-installation"
  },
  {
    "id": "electrical-lighting-005",
    "name": "GFCI Outlet 20A",
    "slug": "gfci-outlet-20a",
    "category": "electrical-lighting",
    "subcategory": "outlets-switches",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Amperage",
        "value": "20 A"
      },
      {
        "key": "Type",
        "value": "Self-test GFCI"
      },
      {
        "key": "Finish",
        "value": "White"
      }
    ],
    "tags": [
      "gfci",
      "white"
    ],
    "images": [
      {
        "src": "/images/products/outlets-switches/gfci-outlet-20a.svg",
        "alt": "GFCI Outlet 20A (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "electrical-repairs-outlets-switches"
  },
  {
    "id": "electrical-lighting-006",
    "name": "USB-C Charging Outlet",
    "slug": "usb-c-charging-outlet",
    "category": "electrical-lighting",
    "subcategory": "outlets-switches",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Amperage",
        "value": "15 A"
      },
      {
        "key": "Ports",
        "value": "USB-A + USB-C 30W"
      },
      {
        "key": "Finish",
        "value": "White"
      }
    ],
    "tags": [
      "usb",
      "white"
    ],
    "images": [
      {
        "src": "/images/products/outlets-switches/usb-c-charging-outlet.svg",
        "alt": "USB-C Charging Outlet (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "electrical-repairs-outlets-switches"
  },
  {
    "id": "electrical-lighting-007",
    "name": "LED Dimmer Switch",
    "slug": "led-dimmer-switch",
    "category": "electrical-lighting",
    "subcategory": "outlets-switches",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Type",
        "value": "Single-pole/3-way"
      },
      {
        "key": "Load",
        "value": "150 W LED"
      },
      {
        "key": "Finish",
        "value": "White"
      }
    ],
    "tags": [
      "dimmer",
      "led-compatible"
    ],
    "images": [
      {
        "src": "/images/products/outlets-switches/led-dimmer-switch.svg",
        "alt": "LED Dimmer Switch (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "electrical-repairs-outlets-switches"
  },
  {
    "id": "electrical-lighting-008",
    "name": "Smart Wi-Fi Dimmer",
    "slug": "smart-wi-fi-dimmer",
    "category": "electrical-lighting",
    "subcategory": "smart-home",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Protocol",
        "value": "Wi-Fi"
      },
      {
        "key": "Neutral",
        "value": "Required"
      },
      {
        "key": "Load",
        "value": "150 W LED"
      }
    ],
    "tags": [
      "smart",
      "dimmer"
    ],
    "images": [
      {
        "src": "/images/products/smart-home/smart-wi-fi-dimmer.svg",
        "alt": "Smart Wi-Fi Dimmer (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "electrical-repairs-outlets-switches"
  },
  {
    "id": "electrical-lighting-009",
    "name": "Video Doorbell (Wired)",
    "slug": "video-doorbell-wired",
    "category": "electrical-lighting",
    "subcategory": "smart-home",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Power",
        "value": "Existing doorbell wiring"
      },
      {
        "key": "Resolution",
        "value": "1080p"
      },
      {
        "key": "Field",
        "value": "150°"
      }
    ],
    "tags": [
      "smart",
      "security"
    ],
    "images": [
      {
        "src": "/images/products/smart-home/video-doorbell-wired.svg",
        "alt": "Video Doorbell (Wired) (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "electrical-repairs-outlets-switches"
  }
];
