// PLACEHOLDER DATA — generated by scripts/generate-placeholder-products.mjs.
// Replace with the real catalog; keep the Product shape.
import type { Product } from "@/lib/data/types";

export const flooringProducts: Product[] = [
  {
    "id": "flooring-001",
    "name": "Desert Oak Luxury Vinyl Plank",
    "slug": "desert-oak-luxury-vinyl-plank",
    "category": "flooring",
    "subcategory": "lvp",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "6 mm"
      },
      {
        "key": "Wear layer",
        "value": "20 mil"
      },
      {
        "key": "Width",
        "value": "7 in"
      },
      {
        "key": "Install",
        "value": "Click-lock"
      }
    ],
    "tags": [
      "waterproof",
      "pet-friendly",
      "light",
      "wood-look"
    ],
    "images": [
      {
        "src": "/images/products/lvp/desert-oak-luxury-vinyl-plank.svg",
        "alt": "Desert Oak Luxury Vinyl Plank (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "flooring-installation"
  },
  {
    "id": "flooring-002",
    "name": "Canyon Hickory Rigid Core Plank",
    "slug": "canyon-hickory-rigid-core-plank",
    "category": "flooring",
    "subcategory": "lvp",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "7 mm"
      },
      {
        "key": "Wear layer",
        "value": "22 mil"
      },
      {
        "key": "Width",
        "value": "9 in"
      },
      {
        "key": "Install",
        "value": "Click-lock"
      }
    ],
    "tags": [
      "waterproof",
      "scratch-resistant",
      "medium",
      "wood-look"
    ],
    "images": [
      {
        "src": "/images/products/lvp/canyon-hickory-rigid-core-plank.svg",
        "alt": "Canyon Hickory Rigid Core Plank (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "flooring-installation"
  },
  {
    "id": "flooring-003",
    "name": "Slate Grey Glue-Down Vinyl",
    "slug": "slate-grey-glue-down-vinyl",
    "category": "flooring",
    "subcategory": "lvp",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "2.5 mm"
      },
      {
        "key": "Wear layer",
        "value": "20 mil"
      },
      {
        "key": "Width",
        "value": "6 in"
      },
      {
        "key": "Install",
        "value": "Glue-down"
      }
    ],
    "tags": [
      "waterproof",
      "commercial-grade",
      "grey"
    ],
    "images": [
      {
        "src": "/images/products/lvp/slate-grey-glue-down-vinyl.svg",
        "alt": "Slate Grey Glue-Down Vinyl (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "flooring-installation"
  },
  {
    "id": "flooring-004",
    "name": "Sierra Maple Laminate",
    "slug": "sierra-maple-laminate",
    "category": "flooring",
    "subcategory": "laminate",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "12 mm"
      },
      {
        "key": "AC rating",
        "value": "AC4"
      },
      {
        "key": "Width",
        "value": "7.5 in"
      },
      {
        "key": "Install",
        "value": "Click-lock"
      }
    ],
    "tags": [
      "scratch-resistant",
      "light",
      "wood-look"
    ],
    "images": [
      {
        "src": "/images/products/laminate/sierra-maple-laminate.svg",
        "alt": "Sierra Maple Laminate (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "flooring-installation"
  },
  {
    "id": "flooring-005",
    "name": "Smoked Walnut Laminate",
    "slug": "smoked-walnut-laminate",
    "category": "flooring",
    "subcategory": "laminate",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "12 mm"
      },
      {
        "key": "AC rating",
        "value": "AC4"
      },
      {
        "key": "Width",
        "value": "7.5 in"
      },
      {
        "key": "Install",
        "value": "Click-lock"
      }
    ],
    "tags": [
      "scratch-resistant",
      "dark",
      "wood-look"
    ],
    "images": [
      {
        "src": "/images/products/laminate/smoked-walnut-laminate.svg",
        "alt": "Smoked Walnut Laminate (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "flooring-installation"
  },
  {
    "id": "flooring-006",
    "name": "White Oak Engineered Plank",
    "slug": "white-oak-engineered-plank",
    "category": "flooring",
    "subcategory": "engineered-hardwood",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "1/2 in"
      },
      {
        "key": "Veneer",
        "value": "3 mm"
      },
      {
        "key": "Width",
        "value": "7.5 in"
      },
      {
        "key": "Finish",
        "value": "Matte UV oil"
      }
    ],
    "tags": [
      "real-wood",
      "light",
      "wide-plank"
    ],
    "images": [
      {
        "src": "/images/products/engineered-hardwood/white-oak-engineered-plank.svg",
        "alt": "White Oak Engineered Plank (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "flooring-installation"
  },
  {
    "id": "flooring-007",
    "name": "Hand-Scraped Hickory Engineered",
    "slug": "hand-scraped-hickory-engineered",
    "category": "flooring",
    "subcategory": "engineered-hardwood",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Thickness",
        "value": "1/2 in"
      },
      {
        "key": "Veneer",
        "value": "2 mm"
      },
      {
        "key": "Width",
        "value": "6.5 in"
      },
      {
        "key": "Finish",
        "value": "Satin urethane"
      }
    ],
    "tags": [
      "real-wood",
      "medium",
      "textured"
    ],
    "images": [
      {
        "src": "/images/products/engineered-hardwood/hand-scraped-hickory-engineered.svg",
        "alt": "Hand-Scraped Hickory Engineered (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "flooring-installation"
  },
  {
    "id": "flooring-008",
    "name": "Calacatta-Look Porcelain 24x48",
    "slug": "calacatta-look-porcelain-24x48",
    "category": "flooring",
    "subcategory": "tile",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "24 × 48 in"
      },
      {
        "key": "Finish",
        "value": "Polished"
      },
      {
        "key": "PEI rating",
        "value": "4"
      },
      {
        "key": "Use",
        "value": "Floor and wall"
      }
    ],
    "tags": [
      "porcelain",
      "white",
      "large-format"
    ],
    "images": [
      {
        "src": "/images/products/tile/calacatta-look-porcelain-24x48.svg",
        "alt": "Calacatta-Look Porcelain 24x48 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "tile-installation"
  },
  {
    "id": "flooring-009",
    "name": "Wood-Look Porcelain Plank 8x48",
    "slug": "wood-look-porcelain-plank-8x48",
    "category": "flooring",
    "subcategory": "tile",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "8 × 48 in"
      },
      {
        "key": "Finish",
        "value": "Matte"
      },
      {
        "key": "PEI rating",
        "value": "5"
      },
      {
        "key": "Use",
        "value": "Floor"
      }
    ],
    "tags": [
      "porcelain",
      "wood-look",
      "medium"
    ],
    "images": [
      {
        "src": "/images/products/tile/wood-look-porcelain-plank-8x48.svg",
        "alt": "Wood-Look Porcelain Plank 8x48 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "tile-installation"
  },
  {
    "id": "flooring-010",
    "name": "Handmade-Look Subway 3x12",
    "slug": "handmade-look-subway-3x12",
    "category": "flooring",
    "subcategory": "tile",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "3 × 12 in"
      },
      {
        "key": "Finish",
        "value": "Glossy"
      },
      {
        "key": "Use",
        "value": "Wall and backsplash"
      }
    ],
    "tags": [
      "ceramic",
      "white",
      "backsplash"
    ],
    "images": [
      {
        "src": "/images/products/tile/handmade-look-subway-3x12.svg",
        "alt": "Handmade-Look Subway 3x12 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "tile-installation"
  },
  {
    "id": "flooring-011",
    "name": "Plush Solution-Dyed Polyester Carpet",
    "slug": "plush-solution-dyed-polyester-carpet",
    "category": "flooring",
    "subcategory": "carpet",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Pile",
        "value": "Plush"
      },
      {
        "key": "Fiber",
        "value": "Solution-dyed polyester"
      },
      {
        "key": "Weight",
        "value": "45 oz"
      },
      {
        "key": "Pad",
        "value": "8 lb rebond included"
      }
    ],
    "tags": [
      "stain-resistant",
      "soft",
      "light"
    ],
    "images": [
      {
        "src": "/images/products/carpet/plush-solution-dyed-polyester-carpet.svg",
        "alt": "Plush Solution-Dyed Polyester Carpet (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "flooring-installation"
  },
  {
    "id": "flooring-012",
    "name": "Textured Loop Berber Carpet",
    "slug": "textured-loop-berber-carpet",
    "category": "flooring",
    "subcategory": "carpet",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Pile",
        "value": "Loop"
      },
      {
        "key": "Fiber",
        "value": "Olefin"
      },
      {
        "key": "Weight",
        "value": "32 oz"
      },
      {
        "key": "Pad",
        "value": "6 lb rebond included"
      }
    ],
    "tags": [
      "durable",
      "pet-friendly",
      "grey"
    ],
    "images": [
      {
        "src": "/images/products/carpet/textured-loop-berber-carpet.svg",
        "alt": "Textured Loop Berber Carpet (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "flooring-installation"
  }
];
