// PLACEHOLDER DATA, generated by scripts/generate-placeholder-products.mjs.
// Replace with the real catalog; keep the Product shape.
import type { Product } from "@/lib/data/types";

export const hvacWaterProducts: Product[] = [
  {
    "id": "hvac-water-001",
    "name": "Smart Learning Thermostat",
    "slug": "smart-learning-thermostat",
    "category": "hvac-water",
    "subcategory": "thermostats",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Wiring",
        "value": "C-wire recommended"
      },
      {
        "key": "Compatibility",
        "value": "Most 24V systems"
      },
      {
        "key": "App",
        "value": "Yes"
      }
    ],
    "tags": [
      "smart",
      "wifi"
    ],
    "images": [
      {
        "src": "/images/products/thermostats/smart-learning-thermostat.svg",
        "alt": "Smart Learning Thermostat (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "handyman-small-repairs"
  },
  {
    "id": "hvac-water-002",
    "name": "Programmable 7-Day Thermostat",
    "slug": "programmable-7-day-thermostat",
    "category": "hvac-water",
    "subcategory": "thermostats",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Wiring",
        "value": "Standard"
      },
      {
        "key": "Compatibility",
        "value": "Most 24V systems"
      }
    ],
    "tags": [
      "programmable"
    ],
    "images": [
      {
        "src": "/images/products/thermostats/programmable-7-day-thermostat.svg",
        "alt": "Programmable 7-Day Thermostat (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "handyman-small-repairs"
  },
  {
    "id": "hvac-water-003",
    "name": "MERV 11 Pleated Filter 20x25x1",
    "slug": "merv-11-pleated-filter-20x25x1",
    "category": "hvac-water",
    "subcategory": "air-filters",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "20 × 25 × 1 in"
      },
      {
        "key": "Rating",
        "value": "MERV 11"
      },
      {
        "key": "Pack",
        "value": "4"
      }
    ],
    "tags": [
      "merv-11"
    ],
    "images": [
      {
        "src": "/images/products/air-filters/merv-11-pleated-filter-20x25x1.svg",
        "alt": "MERV 11 Pleated Filter 20x25x1 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "handyman-small-repairs"
  },
  {
    "id": "hvac-water-004",
    "name": "MERV 13 Pleated Filter 16x25x4",
    "slug": "merv-13-pleated-filter-16x25x4",
    "category": "hvac-water",
    "subcategory": "air-filters",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Size",
        "value": "16 × 25 × 4 in"
      },
      {
        "key": "Rating",
        "value": "MERV 13"
      },
      {
        "key": "Pack",
        "value": "1"
      }
    ],
    "tags": [
      "merv-13",
      "media"
    ],
    "images": [
      {
        "src": "/images/products/air-filters/merv-13-pleated-filter-16x25x4.svg",
        "alt": "MERV 13 Pleated Filter 16x25x4 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "handyman-small-repairs"
  },
  {
    "id": "hvac-water-005",
    "name": "48,000-Grain Water Softener",
    "slug": "48-000-grain-water-softener",
    "category": "hvac-water",
    "subcategory": "water-softeners",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Capacity",
        "value": "48,000 grain"
      },
      {
        "key": "Type",
        "value": "Ion exchange"
      },
      {
        "key": "Household",
        "value": "Up to 5 people"
      }
    ],
    "tags": [
      "softener"
    ],
    "images": [
      {
        "src": "/images/products/water-softeners/48-000-grain-water-softener.svg",
        "alt": "48,000-Grain Water Softener (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "handyman-small-repairs"
  },
  {
    "id": "hvac-water-006",
    "name": "Whole-House Sediment Pre-Filter",
    "slug": "whole-house-sediment-pre-filter",
    "category": "hvac-water",
    "subcategory": "water-softeners",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Micron",
        "value": "5"
      },
      {
        "key": "Housing",
        "value": "Big Blue 20 in"
      },
      {
        "key": "Use",
        "value": "Before softener"
      }
    ],
    "tags": [
      "pre-filter"
    ],
    "images": [
      {
        "src": "/images/products/water-softeners/whole-house-sediment-pre-filter.svg",
        "alt": "Whole-House Sediment Pre-Filter (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "handyman-small-repairs"
  },
  {
    "id": "hvac-water-007",
    "name": "5-Stage Reverse-Osmosis System",
    "slug": "5-stage-reverse-osmosis-system",
    "category": "hvac-water",
    "subcategory": "ro-systems",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Stages",
        "value": "5"
      },
      {
        "key": "Output",
        "value": "75 gpd"
      },
      {
        "key": "Tank",
        "value": "3.2 gal"
      },
      {
        "key": "Faucet",
        "value": "Included"
      }
    ],
    "tags": [
      "ro",
      "under-sink"
    ],
    "images": [
      {
        "src": "/images/products/ro-systems/5-stage-reverse-osmosis-system.svg",
        "alt": "5-Stage Reverse-Osmosis System (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "handyman-small-repairs"
  },
  {
    "id": "hvac-water-008",
    "name": "Tankless RO System",
    "slug": "tankless-ro-system",
    "category": "hvac-water",
    "subcategory": "ro-systems",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Stages",
        "value": "3"
      },
      {
        "key": "Output",
        "value": "600 gpd"
      },
      {
        "key": "Tank",
        "value": "None"
      },
      {
        "key": "Faucet",
        "value": "Included"
      }
    ],
    "tags": [
      "ro",
      "tankless"
    ],
    "images": [
      {
        "src": "/images/products/ro-systems/tankless-ro-system.svg",
        "alt": "Tankless RO System (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "handyman-small-repairs"
  }
];
