// PLACEHOLDER DATA, generated by scripts/generate-placeholder-products.mjs.
// Replace with the real catalog; keep the Product shape.
import type { Product } from "@/lib/data/types";

export const kitchenBathProducts: Product[] = [
  {
    "id": "kitchen-bath-001",
    "name": "Quartz Slab, White with Grey Veining",
    "slug": "quartz-slab-white-with-grey-veining",
    "category": "kitchen-bath",
    "subcategory": "countertops",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Material",
        "value": "Quartz"
      },
      {
        "key": "Thickness",
        "value": "3 cm"
      },
      {
        "key": "Slab",
        "value": "126 × 63 in"
      }
    ],
    "tags": [
      "quartz",
      "white"
    ],
    "images": [
      {
        "src": "/images/products/countertops/quartz-slab-white-with-grey-veining.svg",
        "alt": "Quartz Slab, White with Grey Veining (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "kitchen-refresh-remodeling"
  },
  {
    "id": "kitchen-bath-002",
    "name": "Granite Slab, Black Pearl",
    "slug": "granite-slab-black-pearl",
    "category": "kitchen-bath",
    "subcategory": "countertops",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Material",
        "value": "Granite"
      },
      {
        "key": "Thickness",
        "value": "3 cm"
      },
      {
        "key": "Slab",
        "value": "120 × 70 in"
      }
    ],
    "tags": [
      "granite",
      "dark"
    ],
    "images": [
      {
        "src": "/images/products/countertops/granite-slab-black-pearl.svg",
        "alt": "Granite Slab, Black Pearl (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "kitchen-refresh-remodeling"
  },
  {
    "id": "kitchen-bath-003",
    "name": "White Shaker RTA Base Cabinet 36",
    "slug": "white-shaker-rta-base-cabinet-36",
    "category": "kitchen-bath",
    "subcategory": "cabinets",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Style",
        "value": "Shaker"
      },
      {
        "key": "Box",
        "value": "Plywood"
      },
      {
        "key": "Width",
        "value": "36 in"
      },
      {
        "key": "Finish",
        "value": "White"
      }
    ],
    "tags": [
      "shaker",
      "white",
      "rta"
    ],
    "images": [
      {
        "src": "/images/products/cabinets/white-shaker-rta-base-cabinet-36.svg",
        "alt": "White Shaker RTA Base Cabinet 36 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "kitchen-refresh-remodeling"
  },
  {
    "id": "kitchen-bath-004",
    "name": "Grey Shaker RTA Wall Cabinet 30x36",
    "slug": "grey-shaker-rta-wall-cabinet-30x36",
    "category": "kitchen-bath",
    "subcategory": "cabinets",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Style",
        "value": "Shaker"
      },
      {
        "key": "Box",
        "value": "Plywood"
      },
      {
        "key": "Width",
        "value": "30 in"
      },
      {
        "key": "Finish",
        "value": "Grey"
      }
    ],
    "tags": [
      "shaker",
      "grey",
      "rta"
    ],
    "images": [
      {
        "src": "/images/products/cabinets/grey-shaker-rta-wall-cabinet-30x36.svg",
        "alt": "Grey Shaker RTA Wall Cabinet 30x36 (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "kitchen-refresh-remodeling"
  },
  {
    "id": "kitchen-bath-005",
    "name": "36-inch Vanity with Quartz Top",
    "slug": "36-inch-vanity-with-quartz-top",
    "category": "kitchen-bath",
    "subcategory": "vanities",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Width",
        "value": "36 in"
      },
      {
        "key": "Top",
        "value": "Quartz, single sink"
      },
      {
        "key": "Finish",
        "value": "White"
      }
    ],
    "tags": [
      "white",
      "36-in"
    ],
    "images": [
      {
        "src": "/images/products/vanities/36-inch-vanity-with-quartz-top.svg",
        "alt": "36-inch Vanity with Quartz Top (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "bathroom-remodeling"
  },
  {
    "id": "kitchen-bath-006",
    "name": "60-inch Double Vanity",
    "slug": "60-inch-double-vanity",
    "category": "kitchen-bath",
    "subcategory": "vanities",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Width",
        "value": "60 in"
      },
      {
        "key": "Top",
        "value": "Quartz, double sink"
      },
      {
        "key": "Finish",
        "value": "Navy"
      }
    ],
    "tags": [
      "double",
      "60-in"
    ],
    "images": [
      {
        "src": "/images/products/vanities/60-inch-double-vanity.svg",
        "alt": "60-inch Double Vanity (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "bathroom-remodeling"
  },
  {
    "id": "kitchen-bath-007",
    "name": "Frameless Pivot Shower Door",
    "slug": "frameless-pivot-shower-door",
    "category": "kitchen-bath",
    "subcategory": "shower-doors",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Glass",
        "value": "3/8 in clear tempered"
      },
      {
        "key": "Width",
        "value": "30–34 in"
      },
      {
        "key": "Hardware",
        "value": "Brushed nickel"
      }
    ],
    "tags": [
      "frameless",
      "pivot"
    ],
    "images": [
      {
        "src": "/images/products/shower-doors/frameless-pivot-shower-door.svg",
        "alt": "Frameless Pivot Shower Door (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "bathroom-remodeling"
  },
  {
    "id": "kitchen-bath-008",
    "name": "Semi-Frameless Sliding Tub Door",
    "slug": "semi-frameless-sliding-tub-door",
    "category": "kitchen-bath",
    "subcategory": "shower-doors",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Glass",
        "value": "1/4 in clear tempered"
      },
      {
        "key": "Width",
        "value": "56–60 in"
      },
      {
        "key": "Hardware",
        "value": "Chrome"
      }
    ],
    "tags": [
      "sliding",
      "tub"
    ],
    "images": [
      {
        "src": "/images/products/shower-doors/semi-frameless-sliding-tub-door.svg",
        "alt": "Semi-Frameless Sliding Tub Door (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "bathroom-remodeling"
  }
];
