// PLACEHOLDER DATA, generated by scripts/generate-placeholder-products.mjs.
// Replace with the real catalog; keep the Product shape.
import type { Product } from "@/lib/data/types";

export const paintFinishesProducts: Product[] = [
  {
    "id": "paint-finishes-001",
    "name": "Interior Washable Matte",
    "slug": "interior-washable-matte",
    "category": "paint-finishes",
    "subcategory": "interior-paint",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Sheen",
        "value": "Matte"
      },
      {
        "key": "Coverage",
        "value": "350–400 sq ft/gal"
      },
      {
        "key": "VOC",
        "value": "Low"
      },
      {
        "key": "Use",
        "value": "Walls"
      }
    ],
    "tags": [
      "low-voc",
      "washable"
    ],
    "images": [
      {
        "src": "/images/products/interior-paint/interior-washable-matte.svg",
        "alt": "Interior Washable Matte (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "interior-painting"
  },
  {
    "id": "paint-finishes-002",
    "name": "Interior Trim & Door Enamel",
    "slug": "interior-trim-door-enamel",
    "category": "paint-finishes",
    "subcategory": "interior-paint",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Sheen",
        "value": "Semi-gloss"
      },
      {
        "key": "Coverage",
        "value": "350 sq ft/gal"
      },
      {
        "key": "VOC",
        "value": "Low"
      },
      {
        "key": "Use",
        "value": "Trim, doors, cabinets"
      }
    ],
    "tags": [
      "low-voc",
      "hard-finish"
    ],
    "images": [
      {
        "src": "/images/products/interior-paint/interior-trim-door-enamel.svg",
        "alt": "Interior Trim & Door Enamel (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "interior-painting"
  },
  {
    "id": "paint-finishes-003",
    "name": "Kitchen & Bath Satin",
    "slug": "kitchen-bath-satin",
    "category": "paint-finishes",
    "subcategory": "interior-paint",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Sheen",
        "value": "Satin"
      },
      {
        "key": "Coverage",
        "value": "350–400 sq ft/gal"
      },
      {
        "key": "VOC",
        "value": "Low"
      },
      {
        "key": "Use",
        "value": "Wet rooms"
      }
    ],
    "tags": [
      "mildew-resistant",
      "washable"
    ],
    "images": [
      {
        "src": "/images/products/interior-paint/kitchen-bath-satin.svg",
        "alt": "Kitchen & Bath Satin (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "interior-painting"
  },
  {
    "id": "paint-finishes-004",
    "name": "Elastomeric Stucco Coating",
    "slug": "elastomeric-stucco-coating",
    "category": "paint-finishes",
    "subcategory": "exterior-paint",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Sheen",
        "value": "Flat"
      },
      {
        "key": "Coverage",
        "value": "60–100 sq ft/gal"
      },
      {
        "key": "Use",
        "value": "Stucco, masonry"
      }
    ],
    "tags": [
      "uv-resistant",
      "crack-bridging"
    ],
    "images": [
      {
        "src": "/images/products/exterior-paint/elastomeric-stucco-coating.svg",
        "alt": "Elastomeric Stucco Coating (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "exterior-painting"
  },
  {
    "id": "paint-finishes-005",
    "name": "Exterior Acrylic Trim Paint",
    "slug": "exterior-acrylic-trim-paint",
    "category": "paint-finishes",
    "subcategory": "exterior-paint",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Sheen",
        "value": "Satin"
      },
      {
        "key": "Coverage",
        "value": "350 sq ft/gal"
      },
      {
        "key": "Use",
        "value": "Fascia, trim, doors"
      }
    ],
    "tags": [
      "uv-resistant",
      "fade-resistant"
    ],
    "images": [
      {
        "src": "/images/products/exterior-paint/exterior-acrylic-trim-paint.svg",
        "alt": "Exterior Acrylic Trim Paint (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "exterior-painting"
  },
  {
    "id": "paint-finishes-006",
    "name": "Bonding Primer for Cabinets",
    "slug": "bonding-primer-for-cabinets",
    "category": "paint-finishes",
    "subcategory": "primers-stains",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Base",
        "value": "Water-borne alkyd"
      },
      {
        "key": "Use",
        "value": "Glossy and laminate surfaces"
      }
    ],
    "tags": [
      "adhesion",
      "cabinets"
    ],
    "images": [
      {
        "src": "/images/products/primers-stains/bonding-primer-for-cabinets.svg",
        "alt": "Bonding Primer for Cabinets (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "interior-painting"
  },
  {
    "id": "paint-finishes-007",
    "name": "Stain-Blocking Primer",
    "slug": "stain-blocking-primer",
    "category": "paint-finishes",
    "subcategory": "primers-stains",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Base",
        "value": "Shellac"
      },
      {
        "key": "Use",
        "value": "Water stains, smoke, tannin"
      }
    ],
    "tags": [
      "stain-block"
    ],
    "images": [
      {
        "src": "/images/products/primers-stains/stain-blocking-primer.svg",
        "alt": "Stain-Blocking Primer (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "interior-painting"
  }
];
