// PLACEHOLDER DATA, generated by scripts/generate-placeholder-products.mjs.
// Replace with the real catalog; keep the Product shape.
import type { Product } from "@/lib/data/types";

export const plumbingFixturesProducts: Product[] = [
  {
    "id": "plumbing-fixtures-001",
    "name": "Single-Handle Pull-Down Kitchen Faucet",
    "slug": "single-handle-pull-down-kitchen-faucet",
    "category": "plumbing-fixtures",
    "subcategory": "faucets",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Finish",
        "value": "Spot-resist stainless"
      },
      {
        "key": "Flow",
        "value": "1.8 gpm"
      },
      {
        "key": "Mount",
        "value": "1 or 3 hole"
      }
    ],
    "tags": [
      "stainless",
      "pull-down"
    ],
    "images": [
      {
        "src": "/images/products/faucets/single-handle-pull-down-kitchen-faucet.svg",
        "alt": "Single-Handle Pull-Down Kitchen Faucet (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "garbage-disposal-fixture-installation"
  },
  {
    "id": "plumbing-fixtures-002",
    "name": "Widespread Bathroom Faucet",
    "slug": "widespread-bathroom-faucet",
    "category": "plumbing-fixtures",
    "subcategory": "faucets",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Finish",
        "value": "Matte black"
      },
      {
        "key": "Flow",
        "value": "1.2 gpm"
      },
      {
        "key": "Mount",
        "value": "8 in widespread"
      }
    ],
    "tags": [
      "black",
      "watersense"
    ],
    "images": [
      {
        "src": "/images/products/faucets/widespread-bathroom-faucet.svg",
        "alt": "Widespread Bathroom Faucet (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "garbage-disposal-fixture-installation"
  },
  {
    "id": "plumbing-fixtures-003",
    "name": "Undermount Stainless Single Bowl",
    "slug": "undermount-stainless-single-bowl",
    "category": "plumbing-fixtures",
    "subcategory": "sinks",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Material",
        "value": "16-gauge stainless"
      },
      {
        "key": "Size",
        "value": "32 × 19 in"
      },
      {
        "key": "Depth",
        "value": "10 in"
      }
    ],
    "tags": [
      "stainless",
      "undermount"
    ],
    "images": [
      {
        "src": "/images/products/sinks/undermount-stainless-single-bowl.svg",
        "alt": "Undermount Stainless Single Bowl (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "garbage-disposal-fixture-installation"
  },
  {
    "id": "plumbing-fixtures-004",
    "name": "Farmhouse Fireclay Sink",
    "slug": "farmhouse-fireclay-sink",
    "category": "plumbing-fixtures",
    "subcategory": "sinks",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Material",
        "value": "Fireclay"
      },
      {
        "key": "Size",
        "value": "33 × 20 in"
      },
      {
        "key": "Depth",
        "value": "10 in"
      }
    ],
    "tags": [
      "white",
      "farmhouse"
    ],
    "images": [
      {
        "src": "/images/products/sinks/farmhouse-fireclay-sink.svg",
        "alt": "Farmhouse Fireclay Sink (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "garbage-disposal-fixture-installation"
  },
  {
    "id": "plumbing-fixtures-005",
    "name": "Comfort-Height Elongated Toilet",
    "slug": "comfort-height-elongated-toilet",
    "category": "plumbing-fixtures",
    "subcategory": "toilets",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Flush",
        "value": "1.28 gpf"
      },
      {
        "key": "Height",
        "value": "17 in"
      },
      {
        "key": "Bowl",
        "value": "Elongated"
      }
    ],
    "tags": [
      "watersense",
      "comfort-height"
    ],
    "images": [
      {
        "src": "/images/products/toilets/comfort-height-elongated-toilet.svg",
        "alt": "Comfort-Height Elongated Toilet (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "garbage-disposal-fixture-installation"
  },
  {
    "id": "plumbing-fixtures-006",
    "name": "One-Piece Skirted Toilet",
    "slug": "one-piece-skirted-toilet",
    "category": "plumbing-fixtures",
    "subcategory": "toilets",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Flush",
        "value": "1.28 gpf"
      },
      {
        "key": "Height",
        "value": "17 in"
      },
      {
        "key": "Bowl",
        "value": "Elongated"
      }
    ],
    "tags": [
      "watersense",
      "easy-clean"
    ],
    "images": [
      {
        "src": "/images/products/toilets/one-piece-skirted-toilet.svg",
        "alt": "One-Piece Skirted Toilet (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "garbage-disposal-fixture-installation"
  },
  {
    "id": "plumbing-fixtures-007",
    "name": "50-Gallon Gas Water Heater",
    "slug": "50-gallon-gas-water-heater",
    "category": "plumbing-fixtures",
    "subcategory": "water-heaters",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Capacity",
        "value": "50 gal"
      },
      {
        "key": "Fuel",
        "value": "Natural gas"
      },
      {
        "key": "First-hour rating",
        "value": "80 gal"
      },
      {
        "key": "Warranty",
        "value": "6 yr"
      }
    ],
    "tags": [
      "gas",
      "tank"
    ],
    "images": [
      {
        "src": "/images/products/water-heaters/50-gallon-gas-water-heater.svg",
        "alt": "50-Gallon Gas Water Heater (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "water-heater-replacement"
  },
  {
    "id": "plumbing-fixtures-008",
    "name": "Tankless Gas Water Heater",
    "slug": "tankless-gas-water-heater",
    "category": "plumbing-fixtures",
    "subcategory": "water-heaters",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Flow",
        "value": "9.5 gpm"
      },
      {
        "key": "Fuel",
        "value": "Natural gas"
      },
      {
        "key": "Vent",
        "value": "Direct vent"
      },
      {
        "key": "Warranty",
        "value": "12 yr heat exchanger"
      }
    ],
    "tags": [
      "gas",
      "tankless"
    ],
    "images": [
      {
        "src": "/images/products/water-heaters/tankless-gas-water-heater.svg",
        "alt": "Tankless Gas Water Heater (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "water-heater-replacement"
  },
  {
    "id": "plumbing-fixtures-009",
    "name": "3/4 HP Continuous-Feed Disposal",
    "slug": "3-4-hp-continuous-feed-disposal",
    "category": "plumbing-fixtures",
    "subcategory": "garbage-disposals",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Motor",
        "value": "3/4 HP"
      },
      {
        "key": "Chamber",
        "value": "Stainless"
      },
      {
        "key": "Noise",
        "value": "Quiet series"
      }
    ],
    "tags": [
      "quiet",
      "3/4-hp"
    ],
    "images": [
      {
        "src": "/images/products/garbage-disposals/3-4-hp-continuous-feed-disposal.svg",
        "alt": "3/4 HP Continuous-Feed Disposal (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": true,
    "installServiceSlug": "garbage-disposal-fixture-installation"
  },
  {
    "id": "plumbing-fixtures-010",
    "name": "1/2 HP Continuous-Feed Disposal",
    "slug": "1-2-hp-continuous-feed-disposal",
    "category": "plumbing-fixtures",
    "subcategory": "garbage-disposals",
    "brand": "Placeholder Brand",
    "specs": [
      {
        "key": "Motor",
        "value": "1/2 HP"
      },
      {
        "key": "Chamber",
        "value": "Galvanized"
      }
    ],
    "tags": [
      "1/2-hp",
      "budget"
    ],
    "images": [
      {
        "src": "/images/products/garbage-disposals/1-2-hp-continuous-feed-disposal.svg",
        "alt": "1/2 HP Continuous-Feed Disposal (placeholder image)",
        "width": 800,
        "height": 600
      }
    ],
    "featured": false,
    "installServiceSlug": "garbage-disposal-fixture-installation"
  }
];
